# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       iso-codes
Summary:    ISO code lists and translations
Version:    3.13
Release:    %{?release_prefix:%{release_prefix}.}1.44.%{?dist}%{!?dist:tizen}
VCS:        external/iso-codes#submit/trunk/20121019.111053-0-g6f618715140fa2df57a503b3bd6d4eb70a80f300
Group:      System/Base
License:    LGPLv2+
BuildArch:  noarch
URL:        http://alioth.debian.org/projects/pkg-isocodes/
Source0:    ftp://pkg-isocodes.alioth.debian.org/pub/pkg-isocodes/iso-codes-%{version}.tar.bz2
Source100:  iso-codes.yaml
Requires:   xml-common
BuildRequires:  gettext-tools >= 0.16


%description
This package provides the ISO 639 Language code list, the ISO 4217
Currency code list, the ISO 3166 Territory code list, and ISO 3166-2
sub-territory lists, and all their translations in gettext format.



%package devel
Summary:    Files for development using %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains the pkg-config files for development
when building programs that use %{name}.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post



# << install post
%find_lang iso-codes --all-name









%files -f iso-codes.lang
%defattr(-,root,root,-)
# >> files
%doc ChangeLog README LICENSE
%dir %{_datadir}/xml/iso-codes
%{_datadir}/xml/iso-codes/*.xml
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/pkgconfig/iso-codes.pc
# << files devel

%changelog
* Mon Sep 16 2013 UkJung Kim <ujkim@samsung.com> - submit/trunk/20121019.111053 
- PROJECT: external/iso-codes
- COMMIT_ID: 6f618715140fa2df57a503b3bd6d4eb70a80f300
- PATCHSET_REVISION: 6f618715140fa2df57a503b3bd6d4eb70a80f300
- CHANGE_OWNER: \"UkJung Kim\" <ujkim@samsung.com>
- PATCHSET_UPLOADER: \"UkJung Kim\" <ujkim@samsung.com>
- CHANGE_URL: http://slp-info.sec.samsung.net/gerrit/103460
- PATCHSET_REVISION: 6f618715140fa2df57a503b3bd6d4eb70a80f300
- TAGGER: UkJung Kim <ujkim@samsung.com>
- Gerrit patchset approval info:
- UkJung Kim <ujkim@samsung.com> Verified : 1
- Newton Lee <newton.lee@samsung.com> Code Review : 2
- CHANGE_SUBJECT: Initial commit
- [Version] 3.13
- [Project] GT-I8800
- [Title] Initial commit
- [BinType] PDA
- [Customer] Open
- [Issue#] N/A
- [Problem] N/A
- [Cause] N/A
- [Solution]
- [Team] SCM
- [Developer] UkJung Kim <ujkim@samsung.com>
- [Request] N/A
- [Horizontal expansion] N/A
- [SCMRequest] N/A
* Fri Feb 12 2010 Anas Nashif <anas.nashif@intel.com> - 3.13
- Update to 3.13
